import os
import docker
import time
import requests
import logging

logger = logging.getLogger("Provisioner")

class Provisioner:
    """
    Handles the injection of .st logic into a running OpenPLC container and starts the PLC.
    """
    def __init__(self, docker_manager):
        self.dm = docker_manager
        self.client = docker_manager.client

    async def provision_ied(self, ied_id: str, st_path: str, web_port: int) -> bool:
        """
        Automates the OpenPLC Web UI to upload, compile, and start the .st program.
        """
        base_url = f"http://127.0.0.1:{web_port}"
        session = requests.Session()

        try:
            # 1. Login
            logger.info(f"IED {ied_id}: Authenticating with OpenPLC...")
            login_res = session.post(f"{base_url}/login", data={
                "username": "openplc",
                "password": "openplc"
            }, timeout=5)
            
            if "dashboard" not in login_res.url:
                logger.error(f"IED {ied_id}: Login failed.")
                return False

            # 2. Upload Program
            logger.info(f"IED {ied_id}: Uploading ST code...")
            with open(st_path, 'rb') as f:
                files = {'file': ('trinetra.st', f, 'application/octet-stream')}
                upload_res = session.post(f"{base_url}/programs", files=files, data={
                    "prog_name": "trinetra",
                    "description": "Auto-generated by TRINETRA"
                })
            
            if upload_res.status_code != 200:
                logger.error(f"IED {ied_id}: Upload failed.")
                return False

            # 3. Compile
            # In OpenPLC v3, the upload redirect might trigger compilation or we might need a separate hit
            logger.info(f"IED {ied_id}: Triggering compilation...")
            compile_res = session.post(f"{base_url}/compile-program?prog_name=trinetra.st")
            
            # 4. Wait for Compilation (poll status or just sleep)
            # Compilation can take ~10-20 seconds. We'll wait a bit then start.
            logger.info(f"IED {ied_id}: Compiling logic (this takes ~20s)...")
            await asyncio.sleep(20)

            # 5. Start PLC
            logger.info(f"IED {ied_id}: Starting PLC Runtime...")
            session.get(f"{base_url}/start_plc")
            
            return True

        except Exception as e:
            logger.error(f"Failed to provision IED {ied_id}: {e}")
            return False
